name: node integration and unit tests

on:
  push:
    branches: main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - name: backend dependencies
        run: |
          npm ci

      - name: Unit tests
        run: |
          npm test
